
PASSENGER_ID = 2
PASSENGER_EMAIL = 'test@email.com'
PASSENGER_PASSWORD = '123'

DRIVER_ID = 4
DRIVER_EMAIL = 'pp@gmail.com'
DRIVER_PASSWORD = '123'

ADMIN_ID = 1
ADMIN_EMAIL = 'admin@email.com'
ADMIN_PASSWORD = '123'

ACCOUNT_ACTIVATION_ID = 123456
ACCOUNT_ACTIVATION_ID_EXPIRED = 654321
ACCOUNT_ACTIVATION_ID_NON_EXISTING = 123321

PASSWORD_RESET_CODE = 123456
PASSWORD_RESET_CODE_EXPIRED = 123321
PASSWORD_RESET_USER_ID_EXPIRED = 6

RIDE_ID_FOR_MESSAGES = 1

PASSENGER_ATTACHED_TO_RIDE_ID = 72
PASSENGER_ATTACHED_TO_RIDE_EMAIL = 'passenger.attached.to.ride@gmail.com'

ASSIGNED_DRIVER_PASSWORD = "123"
